name: Provision Infra using Terraform via EC2

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform (apply/destroy)'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: write

jobs:
  provision:
    name: Terraform Infra via EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::650251701672:role/s3-github
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Terraform format
        run: terraform fmt

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan

      - name: Install Python + pip dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip zip

      - name: Build and Upload Lambda Layer ZIP (psycopg2 + openai + boto3 + PyPDF2)
        run: |
          mkdir -p lambda/layer/python
          pip3 install --upgrade pip
          pip3 install \
            --platform manylinux2014_x86_64 \
            --target=lambda/layer/python \
            --implementation cp \
            --python-version 3.9 \
            --only-binary=:all: \
            psycopg2-binary openai boto3 PyPDF2

          echo " Zipping layer..."
          cd lambda/layer
          zip -r ../../layer.zip python

      - name: Upload Lambda Layer to S3
        run: |
          aws s3 cp layer.zip s3://semantic-shit/layers/layer.zip

      - name: Terraform Apply or Destroy
        run: |
          if [[ "${{ github.event.inputs.action }}" == "destroy" ]]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve
          fi
